source 'http://rubygems.org'

gem 'github-pages'
gem 'rake'
gem 'rouge'
gem 'pygments.rb'
gem 'jekyll'
gem 'html-proofer'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
gem 'capistrano', '~> 3.0'
gem 'capistrano-rvm'
gem 'capistrano-gulp', '~> 0.0.2'
